name: Continuous Integration
on: [pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.node-version'
    - run: npm install
    - run: npm test
